version: '2'
services:
  openldap:
    image: dinkel/openldap
    ports:
      - "389:389"
    environment:
      SLAPD_PASSWORD: admin
      SLAPD_DOMAIN: test
    volumes:
      - .:/etc/ldap.dist/prepopulate
  phpldapadmin:
    image: dinkel/phpldapadmin
    ports:
      - "80:80"
    links:
      - openldap
  gerrit:
    image: openfrontier/gerrit
    ports:
      - "8080:8080"
      - "29418:29418"
    links:
      - openldap
    environment:
      WEBURL: http://localhost:8080
      AUTH_TYPE: LDAP
      LDAP_SERVER: openldap
      LDAP_ACCOUNTBASE: ou=people,dc=test
      LDAP_GROUPBASE: ou=groups,dc=test
